@startuml

title __Start New Terminal From IDE (WebSockets)__\n

box "Gwt"
   participant TerminalTabPresenter
   participant TerminalPane
   participant TerminalList
   participant DeckLayoutPanel
   participant TerminalSession
   participant ConsoleProcess
   participant TerminalSessionSocket
   participant WebSocket
   participant JSWebSocket
   participant XTermNative
   participant EventBus
end box

box "RSession"
   participant ConsoleProcessApi
   participant ConsoleProcessTable
   participant ConsoleProc
   participant ConsoleProcessSocket
   participant SocketCallbacks
   participant ProcessSupervisor
   participant ProcessCallbacks
endbox

[-> TerminalTabPresenter: onNewTerminal

activate TerminalTabPresenter
TerminalTabPresenter ->> TerminalPane ++ : activateTerminal
deactivate TerminalTabPresenter

TerminalPane -> TerminalPane: bringToFront
TerminalPane -> TerminalPane: onSelected

TerminalPane -> TerminalTabPresenter: callback
deactivate TerminalPane

activate TerminalTabPresenter
TerminalTabPresenter -> TerminalPane ++ : createTerminal
deactivate TerminalTabPresenter

TerminalPane ->> TerminalList ++ : createNewTerminal
deactivate TerminalPane

TerminalList -> TerminalList: startTerminal
create TerminalSession
TerminalList -> TerminalSession: create
activate TerminalSession
create TerminalSessionSocket
TerminalSession -> TerminalSessionSocket: create
TerminalList ->> TerminalSession: connect

TerminalList -> EventBus: TerminalBusyEvent
deactivate TerminalList

activate ConsoleProcessApi
TerminalSession ->> ConsoleProcessApi: startTerminalRPC
deactivate TerminalSession

activate ConsoleProcessTable
ConsoleProcessApi -> ConsoleProcessTable: createTerminalConsoleProc
create ConsoleProc
ConsoleProcessTable -> ConsoleProc: createTerminalProcess
activate ConsoleProc
ConsoleProc -> ConsoleProcessSocket: ensureServerRunning
activate ConsoleProcessSocket
ConsoleProc -> ConsoleProcessTable: addConsoleProcess
ConsoleProc -> ConsoleProcessTable: saveConsoleProcesses

create SocketCallbacks
ConsoleProc -> SocketCallbacks: create
ConsoleProc -> ConsoleProcessSocket: listen with callbacks
deactivate ConsoleProcessSocket

ConsoleProc -> ConsoleProcessTable: ConsoleProc
deactivate ConsoleProc

ConsoleProcessTable --> ConsoleProcessApi: ConsoleProc
deactivate ConsoleProcessTable

create ConsoleProcess
ConsoleProcessApi -> ConsoleProcess: returns
deactivate ConsoleProcessApi

activate TerminalSession
ConsoleProcess -> TerminalSession: onResponseReceived

activate TerminalSessionSocket
TerminalSession ->> TerminalSessionSocket: connect
deactivate TerminalSession

create WebSocket
TerminalSessionSocket -> WebSocket: create
TerminalSessionSocket ->> WebSocket: open
activate WebSocket

create JSWebSocket
WebSocket ->> JSWebSocket: open
activate JSWebSocket
deactivate WebSocket

JSWebSocket ->> ConsoleProcessSocket: connect
deactivate JSWebSocket
activate ConsoleProcessSocket

ConsoleProcessSocket -> ConsoleProcessSocket: onOpen

TerminalSessionSocket -> TerminalSession: onConnected
activate TerminalSession
TerminalSession ->> ConsoleProcess: start
deactivate TerminalSession
activate ConsoleProcess
ConsoleProcess ->> ConsoleProcessApi: processStartRPC
deactivate TerminalSession
deactivate ConsoleProcess
activate ConsoleProcessApi
ConsoleProcessApi -> ConsoleProcessTable: findProcByHandle
activate ConsoleProcessTable
ConsoleProcessTable -> ConsoleProcessApi: ConsoleProc
deactivate ConsoleProcessTable
ConsoleProcessApi -> ConsoleProc: start
activate ConsoleProc

create ProcessCallbacks
ConsoleProc -> ProcessCallbacks: create
ConsoleProc ->> ProcessSupervisor: runTerminal
deactivate ConsoleProc
activate ProcessSupervisor

ConsoleProcessApi -> TerminalSession: onResponseReceived
deactivate ConsoleProcessApi
activate TerminalSession
TerminalSession -> EventBus: TerminalSessionStartedEvent
deactivate TerminalSession

EventBus -> TerminalPane: onTerminalSessionStarted
activate TerminalPane
TerminalPane -> DeckLayoutPanel: add
TerminalPane -> TerminalPane: showTerminalWidget
@enduml