@startuml

title __TERMINAL's Class Diagram__\n

class TerminalDiagnostics {
   - diagnostic_ : StringBuilder
   + log()
   + getLog()
   + resetLog()
}

class TerminalHelper {
   - warnBeforeClosing_ : boolean
   ~ TerminalHelper()
   + warnBeforeClosing()
   + warnBusyTerminalBeforeCommand()
}

class TerminalInfoDialog {
   - textArea_ : TextArea
   + TerminalInfoDialog()
   - initialize()
   # createMainWidget()
}

class TerminalList {
   - terminals_ : LinkedHashMap<String, TerminalListData>
   - pConsoleProcessFactory_ : Provider<ConsoleProcessFactory>
   # TerminalList()
   - initialize()
   + addTerminal()
   + addTerminal()
   + retitleTerminal()
   - setChildProcs()
   - setCwd()
   + setZombie()
   + setExitCode()
   + setCaption()
   ~ removeTerminal()
   ~ terminateAll()
   + terminalCount()
   + indexOfTerminal()
   + terminalHandleAtIndex()
   + isCaptionAvailable()
   + handleForCaption()
   + autoCloseForHandle()
   - getMetadataForHandle()
   - getFullMetadataForHandle()
   + createNewTerminal()
   + reconnectTerminal()
   + getCaption()
   + getHasSubprocs()
   + haveSubprocs()
   - startTerminal()
   - updateTerminalBusyStatus()
   + iterator()
   + onTerminalSubprocs()
   + onTerminalCwd()
   + debug_dumpTerminalList()
}

class TerminalListData {
   - sessionCreated_ : boolean
   + TerminalListData()
   + getCPI()
   + setSessionCreated()
   + getSessionCreated()
}

class TerminalLocalEcho {
   {static} - ANSI_CTRL_PATTERN : Pattern
   - stopEchoPause_ : long
   - writer_ : Consumer<String>
   - localEcho_ : LinkedList<String>
   + TerminalLocalEcho()
   + echo()
   + isEmpty()
   + write()
   - outputNonEchoed()
   + clear()
   + pause()
   + paused()
   + getDiagnostics()
   + resetDiagnostics()
}

class TerminalPane {
   - closingAll_ : boolean
   - creatingTerminal_ : boolean
   - isRestartInProgress_ : boolean
   - suppressAutoFocus_ : boolean
   - terminalHasChildProcsHandler_ : HandlerRegistration
   - terminalSessionsPanel_ : DeckLayoutPanel
   - terminalTitle_ : Label
   ----
   # TerminalPane()
   - cleanupAfterTerminate()
   - debug_dumpTerminalContext()
   - ensureConnected()
   - ensureTerminal()
   - getLoadedTerminalAtIndex()
   - getLoadedTerminalCount()
   - getSelectedTerminal()
   - getTerminalWithCaption()
   - loadedTerminalWithCaption()
   - loadedTerminalWithHandle()
   - registerChildProcsHandler()
   - renameVisibleTerminalInClient()
   - setFocusOnVisible()
   - setShowTerminalPref()
   - showTerminalWidget()
   - terminalToShowWhenClosing()
   - unregisterChildProcsHandler()
   - updateTerminalToolbar()
   .. WorkbenchPane ..
   # createMainToolbar()
   # createMainWidget()
   + onBeforeSelected()
   + onBeforeUnselected()
   + onSelected()
   .. Display ..
   + activateNamedTerminal()
   + activateTerminal()
   + activeTerminals()
   + addTerminal()
   + clearTerminalScrollbackBuffer()
   + createTerminal()
   + ensureTerminal()
   + interruptTerminal()
   + nextTerminal()
   + previousTerminal()
   + removeTerminal()
   + renameTerminal()
   + repopulateTerminals()
   + sendTerminalToEditor()
   + sendToTerminal()
   + showTerminalInfo()
   + terminateAllTerminals()
   + terminateCurrentTerminal()
   .. Event Handlers ..
   + onServerProcessExit()
   + onSessionSerialization()
   + onSwitchToTerminal()
   + onTerminalSessionStarted()
   + onTerminalSessionStopped()
   + onTerminalSubproc()
   + onTerminalTitle()
}

class TerminalPopupMenu {
   - activeTerminalHandle_ : String
   + TerminalPopupMenu()
   - initialize()
   + getDynamicPopupMenu()
   + getToolbarButton()
   + setActiveTerminal()
   + setActiveTerminalByCaption()
   - refreshActiveTerminal()
   + setNoActiveTerminal()
   + getActiveTerminalHandle()
   + previousTerminal()
   + nextTerminal()
   - addBusyIndicator()
   - trimCaption()
   - getPreviousTerminalHandle()
   - getNextTerminalHandle()
}

class TerminalSession {
   - title_ : String
   - hasChildProcs_ : HasValue<Boolean>
   - connected_ : boolean
   - connecting_ : boolean
   - terminating_ : boolean
   - reloading_ : boolean
   - deferredOutput_ : ArrayList<String>
   - restartSequenceWritten_ : boolean
   - inputQueue_ : StringBuilder
   - inputSequence_ : int
   - newTerminal_ : boolean
   - showAltAfterReload_ : boolean
   - createdByApi_ : boolean
   + TerminalSession()
   - initialize()
   + connect()
   + disconnect()
   + onResizeTerminal()
   + receivedOutput()
   + connectionDisconnected()
   + receivedSendToTerminal()
   + receivedInput()
   - sendUserInput()
   - doLocalEcho()
   + onXTermTitle()
   + setTitle()
   + getTitle()
   + getCaption()
   + clearBuffer()
   + interruptTerminal()
   # addHandlerRegistration()
   # unregisterHandlers()
   # writeError()
   # onLoad()
   # onDetach()
   + setVisible()
   + getHandle()
   + getHasChildProcs()
   + setHasChildProcs()
   + addHasChildProcsChangeHandler()
   + terminate()
   - cleanupAfterTerminate()
   + onSessionSerialization()
   + isConnected()
   # terminalReady()
   - shellSupportsReload()
   - fetchNextChunk()
   + showZombieMessage()
   + writeRestartSequence()
   - setNewTerminal()
   + getProcInfo()
   + getBuffer()
   + getSocket()
}

class TerminalSessionSocket {
   - terminalInputHandler_ : HandlerRegistration
   {static} - PASSWORD_REGEX : String
   {static} + PASSWORD_PATTERN : Pattern
   - keepAliveTimer_ : Timer
   - webSocketPingInterval_ : int
   - connectWebSocketTimer_ : Timer
   - webSocketConnectTimeout_ : int
   + TerminalSessionSocket()
   + connect()
   - switchToRPC()
   + dispatchInput()
   + dispatchOutput()
   + onTerminalDataInput()
   + onConsoleOutput()
   - addHandlerRegistration()
   + unregisterHandlers()
   + disconnect()
   + resetDiagnostics()
   + getConnectionDiagnostics()
   + getLocalEchoDiagnostics()
   - diagnosticError()
   + getTypingLagMsg()
   - receivedKeepAlive()
}

interface Session {
   {abstract} + receivedInput()
   {abstract} + receivedOutput()
   {abstract} + connectionDisconnected()
}

interface ConnectCallback {
   {abstract} + onConnected()
   {abstract} + onError()
}

class InputEchoTimeMonitor {
   - pending_ : LinkedList<InputDatapoint>
   - accumulatedPoints_ : long
   - accumulatedTime_ : long
   ~ InputEchoTimeMonitor()
   ~ inputReceived()
   ~ outputReceived()
   ~ average()
   ~ averageTimeMsg()
}

class InputDatapoint {
   - input_ : String
   - duration_ : long
   ~ InputDatapoint()
   ~ matches()
   ~ duration()
}

class TerminalSocketPacket {
   {static} - keepAlivePrefix : String
   {static} - textPrefix : String
   {static} + textPacket()
   {static} + keepAlivePacket()
   {static} + isKeepAlive()
   {static} + getMessage()
}

class TerminalTab {
   - pConsoleProcessFactory_ : Provider<ConsoleProcessFactory>
   + TerminalTab()
   + closeable()
   + confirmClose()
   - addTerminalProcInfo()
}

abstract class Shim {
   {abstract} ~ onRepopulateTerminals()
   {abstract} ~ confirmClose()
   .. Events ..
   + {abstract} onActivateNamedTerminal(event: ActivateNamedTerminalEvent)
   + {abstract} onAddTerminal(event: AddTerminalEvent)
   + {abstract} onClearTerminal(event: ClearTerminalEvent)
   + {abstract} onCreateTerminal(event: CreateTerminalEvent)
   + {abstract} onRemoveTerminal(event: RemoveTerminalEvent)
   + {abstract} onSendToTerminal(event: SendToTerminalEvent)
   .. Commands ..
   {abstract} + onActivateTerminal()
   {abstract} + onCloseTerminal()
   {abstract} + onRenameTerminal()
   {abstract} + onClearTerminalScrollbackBuffer()
   {abstract} + onPreviousTerminal()
   {abstract} + onNextTerminal()
   {abstract} + onShowTerminalInfo()
   {abstract} + onInterruptTerminal()
   {abstract} + onSendTerminalToEditor()
}

class TerminalTabPresenter {
   + onRepopulateTerminals()
   + confirmClose()
   - shutDownTerminals()
   + TerminalTabPresenter()
   .. Events ..
   + onActivateNamedTerminal()
   + onAddTerminal()
   + onClearTerminal()
   + onCreateTerminal()
   + onRemoveTerminal()
   + onSendToTerminal()
   .. Commands ..
   + onActivateTerminal()
   + onCloseTerminal()
   + onRenameTerminal()
   + onClearTerminalScrollbackBuffer()
   + onPreviousTerminal()
   + onNextTerminal()
   + onShowTerminalInfo()
   + onInterruptTerminal()
   + onSendTerminalToEditor()
}

interface Display {
   {abstract} + activateNamedTerminal()
   {abstract} + activateTerminal()
   {abstract} + activeTerminals()
   {abstract} + addTerminal()
   {abstract} + clearTerminalScrollbackBuffer()
   {abstract} + createTerminal()
   {abstract} + ensureTerminal()
   {abstract} + interruptTerminal()
   {abstract} + nextTerminal()
   {abstract} + previousTerminal()
   {abstract} + removeTerminal()
   {abstract} + renameTerminal()
   {abstract} + repopulateTerminals()
   {abstract} + sendTerminalToEditor()
   {abstract} + sendToTerminal()
   {abstract} + showTerminalInfo()
   {abstract} + terminateAllTerminals()
   {abstract} + terminateCurrentTerminal()
}

TerminalInfoDialog -up-|> ModalDialogBase
TerminalInfoDialog o-- ThemedButton : appendBufferButton_
TerminalList -up-|> Iterable
TerminalList -up-|> Handler
TerminalList -up-|> Handler
TerminalList +-down- TerminalListData
TerminalListData o-- ConsoleProcessInfo : cpi_
TerminalLocalEcho o-- TerminalDiagnostics : diagnostic_
TerminalPane -up-|> Display
TerminalPane o-- TerminalPopupMenu : activeTerminalToolbarButton_
TerminalPane o-- TerminalList : terminals_
TerminalPane o-- WorkbenchServerOperations : server_
TerminalPopupMenu o-- TerminalList : terminals_
TerminalPopupMenu o-- WorkbenchServerOperations : server_
TerminalSession -up-|> Session
TerminalSession -up-|> Handler
TerminalSession -up-|> Handler
TerminalSession -up-|> XTermWidget
TerminalSession o-- HandlerRegistrations : registrations_
TerminalSession o-- TerminalSessionSocket : socket_
TerminalSession o-- ConsoleProcess : consoleProcess_
TerminalSession o-- ConsoleProcessInfo : procInfo_
TerminalSession o-- WorkbenchServerOperations : server_
TerminalSession o-- SessionInfo : sessionInfo_
TerminalSessionSocket -up-|> Handler
TerminalSessionSocket -up-|> Handler
TerminalSessionSocket o-- HandlerRegistrations : registrations_
TerminalSessionSocket o-- Session : session_
TerminalSessionSocket o-- XTermWidget : xterm_
TerminalSessionSocket o-- ConsoleProcess : consoleProcess_
TerminalSessionSocket o-- ConnectCallback : connectCallback_
TerminalSessionSocket o-- InputEchoTimeMonitor : inputEchoTiming_
TerminalSessionSocket o-- Websocket : socket_
TerminalSessionSocket o-- TerminalLocalEcho : localEcho_
TerminalSessionSocket o-- TerminalDiagnostics : diagnostic_
TerminalSessionSocket +-down- Session
TerminalSessionSocket +-down- ConnectCallback
TerminalSessionSocket +-down- InputEchoTimeMonitor
TerminalSessionSocket --> TerminalSocketPacket : <<use>>
InputEchoTimeMonitor +-down- InputDatapoint
InputDatapoint o-- Stopwatch : stopWatch_
TerminalTab o-- Shim : shim_
TerminalTab +-down- Shim
Shim <|-- TerminalTabPresenter
TerminalTabPresenter o-- Display : view_
TerminalTabPresenter o-- TerminalHelper : terminalHelper_
TerminalTabPresenter +-down- Display

right footer

PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
